### ISSUE TITLE
In combination with a querystring the provider may not generate a correct Signature

### ISSUE THREAD

**Issue by rikkreeftenberg** [andyfmiller/LtiLibrary.Owin#1]
Hi Andy,

I've been working with your Lti Libraries and to connect my provider to a BlackBoard system (the Consumer) and I've got a few questions:
(First of all, thanks for a great introduction into Lti! Playing with the online Consumer and Provider made things a lot more clear!)

My provider is called with a querystring.
When generating the Signature at the Consumer side (LtiLibrary.Core.Lti1.LtiRequest.GetLtiRequestViewModel(string consumerSecret)) you first add the querystring(Url.Query), then generate the signature and remove it again before sending it of to the provider.

When checking the Signature at the Provider side (in the 'OnAuthenticate' of the LtiAuthenticationProvider, initialized in the Startup.Auth.cs) you just generate the signature (without adding the querystring!) and check if it matches the received signature. They don't match because a querystring is missing.. 

At what time does the querystring have to be added before calculating the Signature Provider Side?Or am I missing something.

Another question: What sources do you recommend to use? Is the project in GitHub "work in progress"?

Thanks again for all your work!

Rik

**Comment by andyfmiller** [comment]
I pushed a fix in LtiLibrary.Core. OAuthRequest.GenerateSignature (called by provider) now includes the querystring parameters when calculating the signature.

The CodePlex source is stable (for example, I don't think it has this bug).

The GitHub source is a work in progress (for example, it has support for the draft version of Outcomes Management 2.0).

If you think you will be using some of the new stuff that IMS comes out with, then I recommend going with the GitHub source...it will be updated as the new stuff comes out of IMS.

**Comment by rikkreeftenberg** [comment]
Hi Andy.

Many thanks for responding so fast!!
I downloaded the patch and it worked OK.
Now I'll include the LtiLibrary.Core source into my project but as soon as you create a Nuget package I can reference that.

Regards,

Rik

**Comment by andyfmiller** [comment]
Hello Rik,

I just pushed LtiLibrary.Core 1.5.2 to NuGet. Please let me know if you run into any other issues.
