### ISSUE TITLE
Sharing my experience with LtiLibrary.Owin/LtiLibrary.AspNet.Identity.Owin/SecurityHandler.cs

### ISSUE THREAD

**Issue by rikkreeftenberg** [andyfmiller/LtiLibrary.Owin#2]
Hi Andy.

I got version 1.5.2 of the LtiLibrary.Core from NuGet and everythin works as expected. Thanks for that.

There are 2 points I would like to discuss. Just to share my experience with the project:

1* Can't use "LtiLibrary.Owin/LtiLibrary.AspNet.Identity.Owin/SecurityHandler.cs". One of the reasons is I use "AspNet.Identity.EntityFramework.Multitenant" library of James Skimming. The type of the user I have to use is "MultitenantIdentityUser", so the OnAuthenticated handler is like:

        public static async Task OnAuthenticated<TManager, TUser>(LtiAuthenticatedContext context, IEnumerable<Claim> claims = null) 
            where TManager : UserManager<TUser, string>
            where TUser : MultitenantIdentityUser, new()
        {
	etc.
Another reason is I have to create a new "ApplicationUser" (Instead of the TUser), because I added properties to "ApplicationUser". 
It's not a big problem. I just modify the SecurityHandler.cs, but maybe it gives you an idea for future versions.

2* What would you do: Give the new user an AspNetUserRole with userManager.AddToRole(..)? Or just add a Claim of type "ClaimTypes.Role" to the Identity. I'm not sure what is best. What are your thoughts?

Thanks for your time and this project!

Regards,

Rik

**Comment by andyfmiller** [comment]
Hello Rik,

I'm a bit surprised TUser : IdentityUser does not work (assuming MultitenantIdentityUser inherits from IdentityUser. But I'm glad you were able modify the code to work.

I originally thought LtiLibrary.AspNet.Identity.Owin would have a lot more functionality. But in the end, it really only has OnAuthenticated and OnGenerateUserName. And OnGenerateUserName is so specific to each implementation, I fully expect people will write their own.

Regarding roles, I suggest you try both and see which you prefer. Depending on method (and how the multi-tenant library is implemented) the role will be stored in a cookie and/or in the identify database. I prefer to add claims to the identity right before SignIn so they are in the cookie, but not in the database. That way they only apply to the current session.
