### ISSUE TITLE
Invalid OAuth signature or timestamp

### ISSUE THREAD

**Issue by nm4568** [andyfmiller/LtiLibrary.Owin#3]
Hi Andy,

I'm not sure what changed in how the oauth_signature is generated between 1.4.5 (1.4.5418.33006) and your most recent build (pulled from GitHub yesterday) but it is somehow generating an invalid OAuth Signature or Timestamp error within the LTI 1 Certification Test Suite.  I verified that the 1.4.5 library has no issues with the LTI 1 Certification Test Suite.  Also, I have thought of comparing the source files but I am unable to find the source for the 1.4.5 library and I only have a Nuget package.

Please let me know if you need any more information or if I can help in any way.

Thanks,
Nathan Moebus

**Comment by andyfmiller** [comment]
Hello Nathan,

I did make a slight change to the way the signature base string is calculated between 1.5.1 and 1.5.2 to fix https://github.com/andyfmiller/LtiLibrary.Owin/issues/1. I do some more testing and let you know if I find what's wrong.

You can find the 1.4.5 code on CodePlex at http://ltisamples.codeplex.com/.

**Comment by andyfmiller** [comment]
I found the problem. LtiLibrary.Core.OAuth.OAuthRequest.GenerateSignature was double encoding querystring parameters in the signature base string. For example %20 became %2520.

**Comment by nm4568** [comment]
Thanks for the update Andy!

Thanks,
Nathan
