### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Tinkturianec** [andyfmiller/LtiLibrary.Owin#4]
When browser (firefox 40.0.3, chrome 45.0.2454.85) send post request with no data, it don't receive Content-Type header. Server set ContentType field to null, and exception was threw at https://github.com/andyfmiller/LtiLibrary.Owin/blob/master/LtiLibrary.Owin.Security.Lti/OwinRequestExtensions.cs#L55

**Comment by andyfmiller** [comment]
Tinkturianec - Is there a valid LTI post request with no data? I can't think of any. If not, I'll add a check for null or empty like this:

            // All LTI requests should specify ContentType
            if (string.IsNullOrEmpty(request.ContentType)) return false;

**Comment by Tinkturianec** [comment]
lti_message_type and lti_version is required parameters in all versions of standart. And, of course, oauth data. Looks like  there isn't valid LTI request with no data.

**Comment by andyfmiller** [comment]
Fixed in source. See https://github.com/andyfmiller/LtiLibrary.Owin/blob/master/LtiLibrary.Owin.Security.Lti/OwinRequestExtensions.cs#L55
