### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by Korporal** [andyfmiller/LtiLibrary.Owin#6]
The sample web-app allows us to define our role (Teacher, Student) yet when I attempt to define my role (after creating an account) the app crashes saying there is no role "Teacher". Is there some step I must do beforehand?

**Comment by andyfmiller** [comment]
@Korporal Which sample web-app? Would you tell me the steps to take to reproduce the problem?

**Comment by Korporal** [comment]
Hi Andy,

Not at desk just now, but its the solution repo that has all the sample web apps and stuff ( I think it's the LtiSamples repo).

The startup project is already set to Consumer.

I clean / rebuild and start debugging.

I registered as a user then login as that user then assign role to myself.

That fails because there are no roles defined initially in the DB and so the code attempting to add the role to the user, throws an exception.

Were just beginning to explore LTI as we're integrating with Brightspace, your detailed samples are a great help but I need to study it all!

Thanks for prompt response!

Hugh.


Sent from my Windows Phone
________________________________

**Comment by andyfmiller** [comment]
I wonder if the entity framework migrations are not running. The Seed method is coded to create the Teacher role if it does not exist. https://github.com/andyfmiller/LtiSamples/blob/master/Consumer/Migrations/Configuration.cs#L16

But Seed is only run when EF thinks there are migrations to apply. Maybe EF tried to run Seed but it failed. I think in that case the migrations probably stay applied and so Seed is not run again. There is probably a way to force it, but I've forgotten how.
