### ISSUE TITLE
Regarding NuGet package

### ISSUE THREAD

**Issue by glueras** [andyfmiller/LtiLibrary.Owin#8]
Hey Andy,
I am using the LtiLibrary.Owin NuGet package. I have encountered a NullReferenceException in IsAuthenticatedLtiRequestAsync when using the NuGet package, but not when downloading it from GitHub and using my own compiled dll. I see that you previously fixed a similar bug. Did a new NuGet package get published afterwards including this fix?
Sorry the error message is in danish, but I guess you can see the issue.

![image](https://cloud.githubusercontent.com/assets/17729171/19184106/d6fc3b6a-8c7b-11e6-959d-66cf1e8f5133.png)

Thomas

**Comment by andyfmiller** [comment]
It looks like I did not update the NuGet package. I'll look at that today or tomorrow.

**Comment by andyfmiller** [comment]
I just built and uploaded LtiLibrary.Owin.Security.Lti 1.0.0-beta to NuGet. Please let me know if that does not resolve the issue you are seeing.
